<a href="https://colab.research.google.com/github/piaseckazaneta/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
print(dir(np)) #sprawdzamy, jakie mamy metody w numpy

In [ ]:
help(np.array)

Podstawowym obiektem w numpy jest wielowymiarowa tablica (wymiary nazwane są osiami - axes)

In [ ]:
x = np.array([1,3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #liczba elementów

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])

In [ ]:
x.ndim # liczba wymiarów

2

In [ ]:
x.shape #liczba wierszy i kolumn

(2, 2)

In [ ]:
x = np.array([[1,2,4], [4,2,1]])

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)

x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # liczba tablic / po ile wierszy/ po ile kolumn

(2, 2, 3)

Typy danych

In [ ]:
A = np.array([1,2,3])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0,2.3,3.3])

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype = 'float')

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype = 'complex')

In [ ]:
A = np.array([1.0,2.7,3.3], dtype = 'int')

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A # Przypisanie typu 'int' do wartości po przecinku spowodowało, że końcówki zostały ucięte (nie zostaly zaokrąglone)

array([1, 2, 3])

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])

In [ ]:
A.dtype

dtype('bool')

In [ ]:
A = np.array([24,120,230], dtype=np.int8) #Do tworzenia obrazów

<ipython-input-19-98e875234b8a>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24,120,230], dtype=np.int8) #Do tworzenia obrazów


In [ ]:
A.dtype

dtype('int8')

In [ ]:
A = np.array([24,120,230], dtype=np.uint8) #Do tworzenia obrazów, wartości od 0-255

In [ ]:
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10)) #tablica składająca się z samych zer, 4 wiersze, 10 kolumn, domyślnie jest typ 'float'

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Zeros super do tworzenia masek na zdjęcie

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int') #wypełnienie tablicy konkretną wartością

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10) #wygeneruje dane w postaci array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10) #bez 10

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.linspace(start=0, stop=1, num=11) #ile elementów chcemy wygenerowac z przedizału, równo rozlozone

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) # zmiana z tablicy 1,15 na 3,5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B #operacje wykonywane na elementach tablicy (tak samo odejmowanie, mnożenie, dzielenie)

array([6, 0, 7, 4])

In [ ]:
A + 3 # dodawanie do każdego elementu stałej wartości (tak samo odej, mnoz, dziel)

array([6, 4, 7, 5])

In [ ]:
np.add(A, B) # metoda add do dodawania tablic

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B) # metoda subtract do odejmowania tablic

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B) #do mnozenia tablic

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B) # do dzielenia tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

Mnożenie macierzowe

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [ ]:
X * Y #zwykłe mnożenie

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y) #mnożenie macierzowe !!!!!! wiersz * kolumna i wiersz * kolumna

array([[  3,   6],
       [-12,   0]])

MNOŻENIE MACIERZOWE NIE JEST PRZEMIENNE!

In [ ]:
X @ Y # mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0) # seed - ziarno losowania, jeśli jest ustawione 0 to wynik zawsze będzie ten sam

In [ ]:
np.random.randn() #zwróci losową wartość z rozkładu normalnego

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4) # parametr pierwszy - liczba wierszy, drugi - liczba kolumn

array([[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
       [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
       [-0.17992484, -1.07075262,  1.05445173, -0.40317695]])

In [ ]:
np.random.rand()

0.8811031971111616

In [ ]:
np.random.randint(10) #zwróci liczbę całkowitą mniejszą niż 10, większą niż 0

5

In [ ]:
np.random.randint(low=10, high=101) #generuje losową liczbę dwucyfrową

35

In [ ]:
np.random.randint(low=10, high=101, size=10) #generuje losową liczbę dwucyfrową z 10cioma elementami

array([90, 70, 71, 93, 43, 42, 80, 95, 41, 23])

In [ ]:
np.random.choice([4, 2, 1, 3]) #zwróci losowy element z listy

3

In [ ]:
np.random.choice(['python', 'zaba'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) #przetasuje elementy
data

array([3, 7, 1, 5, 6, 0, 9, 4, 8, 2])

Podstawowe funkcje NumPy

In [ ]:
np.exp(1) #stała Eulera

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2,3,1]) #sprawdza czy zwraca nam wartosc true/false

True

In [ ]:
np.any([0, 0, 1]) #sprawdza czy jakikolwiek obiekt jest prawdą / czasem możemy szukać czy mamy gdzies 0 w tablicy

True

In [ ]:
A = np.random.rand(5) #przypuśćmy, że mamy 5 klas, model nam zwróci 5 wartości i chcemy wiedzieć co dalej
A

array([0.16249293, 0.61555956, 0.12381998, 0.84800823, 0.80731896])

In [ ]:
np.argmax(A)# probujemy uzyc funkcji, ktora wycignie nam indeks gdzie nasza tablica przyjmuje wartosc najwiekszą

3

In [ ]:
A[np.argmax(A)] #wycina wartość o najwyzeszej wartosci

0.8480082293222344

In [ ]:
np.argmin(A) #indeks wartosci najnizszej

2

In [ ]:
np.argsort(A) #sortuje indeksy od najwyzszych do najnizszych wartosic

array([2, 0, 1, 4, 3])

In [ ]:
np.max(A) #wartosc najwyzsza w tablicy

0.8480082293222344

In [ ]:
np.min(A) #wartosc najnizsza

0.12381998284944151

In [ ]:
np.median(A)

0.6155595642838442

In [ ]:
np.std(A)

0.3110230689083066

In [3]:
A = np.arange(start=-10, stop=10, step=0.5)
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [5]:
np.bitwise_and(A > -5, A < 5) #zwórci nam True, kiedy element tablicy będzie spełniał warunek AND (bez funkcji 'bitwise' python nie wiedziałby co ma zrobić z tym przedziałem)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [8]:
np.bitwise_or(A < -5, A > 5) # warunek OR

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])