<a href="https://colab.research.google.com/github/piaseckazaneta/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
print(dir(np)) #sprawdzamy, jakie mamy metody w numpy

In [ ]:
help(np.array)

Podstawowym obiektem w numpy jest wielowymiarowa tablica (wymiary nazwane są osiami - axes)

In [ ]:
x = np.array([1,3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #liczba elementów

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])

In [ ]:
x.ndim # liczba wymiarów

2

In [ ]:
x.shape #liczba wierszy i kolumn

(2, 2)

In [ ]:
x = np.array([[1,2,4], [4,2,1]])

In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)

x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # liczba tablic / po ile wierszy/ po ile kolumn

(2, 2, 3)

Typy danych

In [3]:
A = np.array([1,2,3])

In [4]:
A.dtype

dtype('int64')

In [5]:
A = np.array([1.0,2.3,3.3])

In [6]:
A.dtype

dtype('float64')

In [7]:
A = np.array([1,2,3], dtype = 'float')

In [8]:
A.dtype

dtype('float64')

In [9]:
A = np.array([1,2,3], dtype = 'complex')

In [10]:
A = np.array([1.0,2.7,3.3], dtype = 'int')

In [11]:
A.dtype

dtype('int64')

In [13]:
A # Przypisanie typu 'int' do wartości po przecinku spowodowało, że końcówki zostały ucięte (nie zostaly zaokrąglone)

array([1, 2, 3])

In [14]:
A

array([1, 2, 3])

In [15]:
A = np.array([True, False])

In [16]:
A.dtype

dtype('bool')

In [19]:
A = np.array([24,120,230], dtype=np.int8) #Do tworzenia obrazów

<ipython-input-19-98e875234b8a>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24,120,230], dtype=np.int8) #Do tworzenia obrazów


In [18]:
A.dtype

dtype('int8')

In [22]:
A = np.array([24,120,230], dtype=np.uint8) #Do tworzenia obrazów, wartości od 0-255

In [21]:
A.dtype

dtype('uint8')

Tworzenie tablic

In [23]:
np.zeros(shape=(4,10)) #tablica składająca się z samych zer, 4 wiersze, 10 kolumn, domyślnie jest typ 'float'

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Zeros super do tworzenia masek na zdjęcie

In [25]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.full(shape=(3,3), fill_value=4, dtype='int') #wypełnienie tablicy konkretną wartością

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [28]:
np.arange(10) #wygeneruje dane w postaci array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(start=5, stop=10) #bez 10

array([5, 6, 7, 8, 9])

In [31]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [35]:
np.linspace(start=0, stop=1, num=11) #ile elementów chcemy wygenerowac z przedizału, równo rozlozone

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [38]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
A.reshape((3,5)) # zmiana z tablicy 1,15 na 3,5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])