<a href="https://colab.research.google.com/github/piaseckazaneta/data-science-bootcamp/blob/main/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Norma wektora jest uogólnieniem pojęcia długości wektora

In [ ]:
v1 = np.array([-1, 4]) #zdefiniowany wektor, w nawiasie współrzędne wektora
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1) # liczenie normy wektorowej w przestrzeni R2

4.123105625617661

Liczenie długości wektora w przestrzeni Rn

In [ ]:
v2 = np.array([-10, 10, 13]) #liczenie długości wektra w przestrzeni R3
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płąszczyźnie

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

In [ ]:
np.linalg.norm(p - q)

5.0990195135927845

Odległość dwóch punktów w przestrzeni Rn

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])


Mnożenie macierzy - aby pomnożyć dwie macierze, liczba kolumn z pierwszej macierzy musi być równa liczbie wierwszy w drugiej macierzy

In [ ]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x)
print(y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
Z = np.dot(x, y) # mnożenie macierzy
Z

array([[ 2],
       [-6]])

Rozwiązywanie układów równań AX = B

Układ równań:
2x + 4y = 10
x - y = -1

Rozwiązanie:
x = 1
y = 2

In [4]:
# Macierz współczynników
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [6]:
# Macierz wyrazów wolnych
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [7]:
# Macierz odwrotna do macierzy A (A-1)
A_inv = np.linalg.inv(A)

In [9]:
# Mnożenie ( X= A-1 * B)
X = np.dot(A_inv, B)
print(X)


[[1.]
 [2.]]
